### ISSUE TITLE
Some of these can be incorporated in Babel

### ISSUE THREAD

**Issue by hzoo** [yiminghe/babel-runtime-loose#2]
Just FYI, maybe you didn't know but you can suggest certain changes for loose mode

Ref https://github.com/babel/babel/pull/4850

**Comment by yiminghe** [comment]
Ok, I will.

I am building a standalone library, 4850 is just what I want, I think I can switch to babel7 loose mode at an appropriate time

**Comment by hzoo** [comment]
Cool I'll close
